In [2]:
#NumPY
import numpy as np

# DataTypes & Attributes

In [3]:
# numpy's main datatypes in ndarray
a1 = np.array([1,3,4])
a1

array([1, 3, 4])

In [7]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4, 5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [23]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype

dtype('int64')

In [11]:
a1.size

3

In [5]:
# Create a DtaFrame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [6]:
semple_array = np.array([1,2,3])

## 2. Creating arrays

In [7]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [8]:
onces = np.ones((2, 3))

In [20]:
onces

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
onces.dtype
type(onces)

numpy.ndarray

In [9]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
range_array = np.random.randint(0, 10, size=(3, 5))
range_array

array([[1, 7, 7, 4, 7],
       [1, 7, 3, 1, 8],
       [9, 5, 4, 2, 7]])

In [11]:
range_array.shape

(3, 5)

In [12]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.59163873, 0.54179913, 0.06159001],
       [0.00349838, 0.74888955, 0.3714693 ],
       [0.26708224, 0.22600841, 0.23385602],
       [0.48076405, 0.00385537, 0.87586589],
       [0.29594963, 0.78136899, 0.03646349]])

In [15]:
random_array_3.shape

(5, 3)

In [13]:
# Pseudo-random numebrs
np.random.seed(seed=0)
random_array = np.random.randint(99, size=(7, 4))
random_array

array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [14]:
random_array_6 = np.random.random(size=(7, 4))
random_array_6

array([[0.83261985, 0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547, 0.66676672]])

## 3. Viewing arrays and matices

In [15]:
np.unique(random_array_6)

array([0.0187898 , 0.06022547, 0.11827443, 0.14335329, 0.26455561,
       0.3595079 , 0.41466194, 0.43703195, 0.45615033, 0.46147936,
       0.52184832, 0.56843395, 0.61209572, 0.616934  , 0.6176355 ,
       0.63992102, 0.66676672, 0.6818203 , 0.6976312 , 0.77423369,
       0.77815675, 0.78052918, 0.79915856, 0.83261985, 0.87001215,
       0.94374808, 0.94466892, 0.97861834])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a3[:, :, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

## Manipulating & comparing arrays

### arthmetic

In [62]:
a1

array([1, 3, 4])

In [65]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [66]:
a1 - ones

array([0., 2., 3.])

In [68]:
a1 + ones

array([2., 4., 5.])

In [69]:
a1 * a2

array([[ 1. ,  6. , 13.2],
       [ 4. , 15. , 26. ]])

In [70]:
a1 % a2

array([[0. , 1. , 0.7],
       [1. , 3. , 4. ]])

In [16]:
a1 / a2

array([[1.        , 1.5       , 1.21212121],
       [0.25      , 0.6       , 0.61538462]])

In [18]:
a1 // a2

array([[1., 1., 1.],
       [0., 0., 0.]])

In [19]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [23]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [21]:
a1 + onces

array([[2., 4., 5.],
       [2., 4., 5.]])

In [25]:
np.add(a1, onces)

array([[2., 4., 5.],
       [2., 4., 5.]])

In [26]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [27]:
np.exp(a1)

array([ 2.71828183, 20.08553692, 54.59815003])

In [28]:
np.exp(a1)

array([ 2.71828183, 20.08553692, 54.59815003])

In [ ]:
np.log()