In [3]:
#NumPY
import numpy as np

# DataTypes & Attributes

In [4]:
# numpy's main datatypes in ndarray
a1 = np.array([1,3,4])
a1

array([1, 3, 4])

In [7]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4, 5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [23]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype

dtype('int64')

In [11]:
a1.size

3

In [6]:
# Create a DtaFrame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [16]:
semple_array = np.array([1,2,3])

## 2. Creating arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
onces = np.ones((2, 3))

In [20]:
onces

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
onces.dtype
type(onces)

numpy.ndarray

In [27]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [9]:
range_array = np.random.randint(0, 10, size=(3, 5))
range_array

array([[1, 0, 6, 1, 3],
       [9, 8, 1, 8, 3],
       [4, 5, 2, 7, 4]])

In [11]:
range_array.shape

(3, 5)

In [13]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.14346312, 0.12099974, 0.54655999],
       [0.93223341, 0.6408474 , 0.20459602],
       [0.88808183, 0.18452834, 0.26832709],
       [0.37131056, 0.06659667, 0.15723619],
       [0.30096972, 0.93109149, 0.63647881]])

In [15]:
random_array_3.shape

(5, 3)

In [43]:
# Pseudo-random numebrs
np.random.seed(seed=0)
random_array = np.random.randint(99, size=(7, 4))
random_array

array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [48]:
random_array_6 = np.random.random(size=(7, 4))
random_array_6

array([[0.29007761, 0.61801543, 0.4287687 , 0.13547406],
       [0.29828233, 0.56996491, 0.59087276, 0.57432525],
       [0.65320082, 0.65210327, 0.43141844, 0.8965466 ],
       [0.36756187, 0.43586493, 0.89192336, 0.80619399],
       [0.70388858, 0.10022689, 0.91948261, 0.7142413 ],
       [0.99884701, 0.1494483 , 0.86812606, 0.16249293],
       [0.61555956, 0.12381998, 0.84800823, 0.80731896]])