In [4]:
#NumPY
import numpy as np

# DataTypes & Attributes

In [5]:
# numpy's main datatypes in ndarray
a1 = np.array([1,3,4])
a1

array([1, 3, 4])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2.0,3.3],
               [4, 5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype

dtype('int64')

In [14]:
a1.size

3

In [15]:
# Create a DtaFrame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [16]:
semple_array = np.array([1,2,3])

## 2. Creating arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
onces = np.ones((2, 3))

In [20]:
onces

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
onces.dtype
type(onces)

numpy.ndarray

In [22]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
range_array = np.random.randint(0, 10, size=(3, 5))
range_array

array([[3, 3, 8, 6, 8],
       [2, 2, 3, 0, 6],
       [0, 6, 9, 6, 3]])

In [25]:
range_array.shape

(3, 5)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.22468733, 0.38802435, 0.43171176],
       [0.47706492, 0.1083056 , 0.55631019],
       [0.43647043, 0.93754164, 0.51911256],
       [0.89877342, 0.1035597 , 0.68153001],
       [0.90018919, 0.92138354, 0.20287756]])

In [27]:
random_array_3.shape

(5, 3)

In [28]:
# Pseudo-random numebrs
np.random.seed(seed=0)
random_array = np.random.randint(99, size=(7, 4))
random_array

array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [29]:
random_array_6 = np.random.random(size=(7, 4))
random_array_6

array([[0.83261985, 0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547, 0.66676672]])

## 3. Viewing arrays and matices

In [30]:
np.unique(random_array_6)

array([0.0187898 , 0.06022547, 0.11827443, 0.14335329, 0.26455561,
       0.3595079 , 0.41466194, 0.43703195, 0.45615033, 0.46147936,
       0.52184832, 0.56843395, 0.61209572, 0.616934  , 0.6176355 ,
       0.63992102, 0.66676672, 0.6818203 , 0.6976312 , 0.77423369,
       0.77815675, 0.78052918, 0.79915856, 0.83261985, 0.87001215,
       0.94374808, 0.94466892, 0.97861834])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a3[:, :, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

## Manipulating & comparing arrays

### arthmetic

In [33]:
a1

array([1, 3, 4])

In [34]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [35]:
a1 - ones

array([0., 2., 3.])

In [36]:
a1 + ones

array([2., 4., 5.])

In [37]:
a1 * a2

array([[ 1. ,  6. , 13.2],
       [ 4. , 15. , 26. ]])

In [38]:
a1 % a2

array([[0. , 1. , 0.7],
       [1. , 3. , 4. ]])

In [39]:
a1 / a2

array([[1.        , 1.5       , 1.21212121],
       [0.25      , 0.6       , 0.61538462]])

In [40]:
a1 // a2

array([[1., 1., 1.],
       [0., 0., 0.]])

In [41]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [42]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [43]:
a1 + onces

array([[2., 4., 5.],
       [2., 4., 5.]])

In [44]:
np.add(a1, onces)

array([[2., 4., 5.],
       [2., 4., 5.]])

In [45]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [46]:
np.exp(a1)

array([ 2.71828183, 20.08553692, 54.59815003])

In [47]:
np.exp(a1)

array([ 2.71828183, 20.08553692, 54.59815003])

In [48]:
np.log(a1)

array([0.        , 1.09861229, 1.38629436])

### Aggregation
Aggregation = performing the same operation on a number of things

In [49]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [50]:
sum(listy_list)

6

In [51]:
sum(a1)

np.int64(8)

In [52]:
np.sum(a1)

np.int64(8)

use Python's methods (`sum()`) on Python dataypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [53]:
massive_array[:10]

NameError: name 'massive_array' is not defined

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
print(np.__version__)

In [ ]:
np.min(a2)

In [ ]:
# standerd deviation = a measure of how spread out a grorp of numebrs is 
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is defferent
# Higher variace = wider range of numbers
# Lower variance = Lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = sqareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
np.std(high_var_array).plot

In [54]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

NameError: name 'high_var_array' is not defined

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping && transposing

In [55]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [56]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [57]:
a2.shape

(2, 3)

In [58]:
a2.reshape(2, 3)

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
a3.reshape(2, 3, 1)

ValueError: cannot reshape array of size 18 into shape (2,3,1)

In [60]:
a2, a2.shape, a3, a3.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [61]:
a2_reshaped = a2.reshape(2, 3, 1)

In [62]:
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [64]:
a2.shape

(2, 3)

In [65]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [66]:
a2.T.shape

(3, 2)

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
a3.shape

(2, 3, 3)

In [69]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [70]:
import pandas as pd
table = pd.DataFrame(a2.T)
table

0    1
0  1.0  4.0
1  2.0  5.0
2  3.3  6.5

In [71]:
import pandas as pd
table = pd.DataFrame(a2)
table

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### Dot product

In [72]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1, mat2, mat1.shape, mat2.shape

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]),
 (5, 3),
 (5, 3))

In [73]:
# Element-wise multipieation (Hadamard produet)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [74]:
# Dot product
np.dot(mat1.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

#### Dot product exmaple (nut butter sales)

In [75]:
np.random.seed(0)
sales_amounts = np.random.randint(99, size=(5, 3))
sales_amounts

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [76]:
prise_amounts = np.random.randint(99, size=(1, 3)).T
prise_amounts

array([[65],
       [39],
       [87]])

In [77]:
np.dot(sales_amounts, prise_amounts)

array([[10261],
       [ 7751],
       [ 9346],
       [16041],
       [11234]])

In [78]:
import pandas as pd
sales_amounts_df = pd.DataFrame(sales_amounts)
sales_amounts_df

0   1   2
0  44  47  64
1  67  67   9
2  83  21  36
3  87  70  88
4  88  12  58

In [79]:
sales_amounts_df.rename(columns={0 : 'Almond', 1 : 'Peanut', 2 : 'Cashew'}, inplace=True)
sales_amounts_df.rename(index={0 : 'Mon', 1 : 'Tues', 2 : 'Wed', 3 : 'Thurs', 4 : 'Fri'}, inplace=True)
sales_amounts_df

Almond  Peanut  Cashew
Mon        44      47      64
Tues       67      67       9
Wed        83      21      36
Thurs      87      70      88
Fri        88      12      58

In [80]:
sales_amounts_df["Total"] = np.dot(sales_amounts, prise_amounts)
sales_amounts_df

Almond  Peanut  Cashew  Total
Mon        44      47      64  10261
Tues       67      67       9   7751
Wed        83      21      36   9346
Thurs      87      70      88  16041
Fri        88      12      58  11234

### Comparison Operators

In [81]:
a1 > a2

array([[False,  True,  True],
       [False, False, False]])

In [82]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [83]:
a1 == a2

array([[ True, False, False],
       [False, False, False]])

In [84]:
a1 > 5

array([False, False, False])

In [85]:
a1 < 5

array([ True,  True,  True])

### 5. Sorting arrays

In [86]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[8, 1, 5, 9, 8],
       [9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8]])

In [87]:
random_array.shape

(3, 5)

In [88]:
np.sort(random_array)

array([[1, 5, 8, 8, 9],
       [0, 3, 3, 4, 9],
       [0, 2, 3, 5, 8]])

In [89]:
np.argsort(random_array)

array([[1, 2, 0, 4, 3],
       [3, 2, 4, 1, 0],
       [1, 2, 3, 0, 4]])

In [90]:
np.argsort(random_array)

array([[1, 2, 0, 4, 3],
       [3, 2, 4, 1, 0],
       [1, 2, 3, 0, 4]])

In [91]:
np.argmin(a1)

np.int64(0)

In [92]:
np.argmax(a1)

np.int64(2)

In [103]:
np.argmax(random_array, axis=0)

array([1, 1, 0, 0, 0])

### Practical Example - Numpy in action!!

<img src="images/panda.png"/>

In [98]:
from matplotlib.image import imread
panda = imread('images/panda.png')
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [99]:
panda.size, panda.shape, panda.ndim, panda.dtype

(24465000, (2330, 3500, 3), 3, dtype('float32'))

In [101]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png"/>

In [106]:
car= imread("images/car-photo.png")
car[1]

array([[0.44313726, 0.43529412, 0.40392157, 1.        ],
       [0.3137255 , 0.31764707, 0.27450982, 1.        ],
       [0.2       , 0.21176471, 0.14117648, 1.        ],
       ...,
       [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
       [0.49803922, 0.52156866, 0.39607844, 1.        ],
       [0.4       , 0.42745098, 0.34117648, 1.        ]],
      shape=(575, 4), dtype=float32)