In [1]:
#NumPY
import numpy as np

# DataTypes & Attributes

In [2]:
# numpy's main datatypes in ndarray
a1 = np.array([1,3,4])
a1

array([1, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4, 5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype

dtype('int64')

In [11]:
a1.size

3

In [12]:
# Create a DtaFrame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [13]:
semple_array = np.array([1,2,3])

## 2. Creating arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int64')

In [16]:
onces = np.ones((2, 3))

In [17]:
onces

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
onces.dtype
type(onces)

numpy.ndarray

In [19]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
range_array = np.random.randint(0, 10, size=(3, 5))
range_array

array([[5, 2, 1, 6, 1],
       [3, 8, 8, 5, 9],
       [8, 7, 7, 6, 2]])

In [22]:
range_array.shape

(3, 5)

In [23]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.8982309 , 0.41950631, 0.99421432],
       [0.92626897, 0.72911316, 0.84922195],
       [0.15771831, 0.30753455, 0.95302606],
       [0.75630241, 0.58961962, 0.15265441],
       [0.57923341, 0.35643956, 0.00478632]])

In [24]:
random_array_3.shape

(5, 3)

In [25]:
# Pseudo-random numebrs
np.random.seed(seed=0)
random_array = np.random.randint(99, size=(7, 4))
random_array

array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [26]:
random_array_6 = np.random.random(size=(7, 4))
random_array_6

array([[0.83261985, 0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547, 0.66676672]])

## 3. Viewing arrays and matices

In [27]:
np.unique(random_array_6)

array([0.0187898 , 0.06022547, 0.11827443, 0.14335329, 0.26455561,
       0.3595079 , 0.41466194, 0.43703195, 0.45615033, 0.46147936,
       0.52184832, 0.56843395, 0.61209572, 0.616934  , 0.6176355 ,
       0.63992102, 0.66676672, 0.6818203 , 0.6976312 , 0.77423369,
       0.77815675, 0.78052918, 0.79915856, 0.83261985, 0.87001215,
       0.94374808, 0.94466892, 0.97861834])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a3[:, :, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

## Manipulating & comparing arrays

### arthmetic

In [30]:
a1

array([1, 3, 4])

In [31]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [32]:
a1 - ones

array([0., 2., 3.])

In [33]:
a1 + ones

array([2., 4., 5.])

In [34]:
a1 * a2

array([[ 1. ,  6. , 13.2],
       [ 4. , 15. , 26. ]])

In [35]:
a1 % a2

array([[0. , 1. , 0.7],
       [1. , 3. , 4. ]])

In [36]:
a1 / a2

array([[1.        , 1.5       , 1.21212121],
       [0.25      , 0.6       , 0.61538462]])

In [37]:
a1 // a2

array([[1., 1., 1.],
       [0., 0., 0.]])

In [38]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [39]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [40]:
a1 + onces

array([[2., 4., 5.],
       [2., 4., 5.]])

In [41]:
np.add(a1, onces)

array([[2., 4., 5.],
       [2., 4., 5.]])

In [42]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [43]:
np.exp(a1)

array([ 2.71828183, 20.08553692, 54.59815003])

In [44]:
np.exp(a1)

array([ 2.71828183, 20.08553692, 54.59815003])

In [45]:
np.log(a1)

array([0.        , 1.09861229, 1.38629436])

### Aggregation
Aggregation = performing the same operation on a number of things

In [46]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [47]:
sum(listy_list)

6

In [48]:
sum(a1)

np.int64(8)

In [49]:
np.sum(a1)

np.int64(8)

use Python's methods (`sum()`) on Python dataypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [50]:
massive_array[:10]

NameError: name 'massive_array' is not defined

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
print(np.__version__)

In [ ]:
np.min(a2)

In [ ]:
# standerd deviation = a measure of how spread out a grorp of numebrs is 
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is defferent
# Higher variace = wider range of numbers
# Lower variance = Lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = sqareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [51]:
np.std(high_var_array).plot

NameError: name 'high_var_array' is not defined

In [52]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

NameError: name 'high_var_array' is not defined

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping && transposing

In [ ]:
a2

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3)

In [ ]:
a3.reshape(2, 3, 1)

In [ ]:
a2, a2.shape, a3, a3.shape

In [ ]:
a2_reshaped = a2.reshape(2, 3, 1)

In [ ]:
a2_reshaped * a3

In [ ]:
a2

In [53]:
a2.shape

(2, 3)

In [54]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [55]:
a2.T.shape

(3, 2)

In [56]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [57]:
a3.shape

(2, 3, 3)

In [58]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [59]:
import pandas as pd
table = pd.DataFrame(a2.T)
table

0    1
0  1.0  4.0
1  2.0  5.0
2  3.3  6.5

In [60]:
import pandas as pd
table = pd.DataFrame(a2)
table

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### Dot product

In [64]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1, mat2, mat1.shape, mat2.shape

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]),
 (5, 3),
 (5, 3))

In [65]:
# Element-wise multipieation (Hadamard produet)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [68]:
# Dot product
np.dot(mat1.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])